#!/bin/sh
set -eu

rm -f /var/run/mysqld/*
mkdir -p /var/lib/mysql/ /var/run/mysqld/ /docker-entrypoint-initdb.d/
chown mysql:mysql /var/lib/mysql/ /var/run/mysqld/

if [ ! -f /var/lib/mysql/ibdata1 ]; then
	/usr/bin/mysqld-initialize
fi
